[theme]
base                     = "dark"
backgroundColor          = "#141414"
secondaryBackgroundColor = "#1e1e1e"
primaryColor             = "#22d3ee"
textColor                = "#e8e8e8"
font                     = "sans serif"

[server]
headless = true
