[theme]
base                     = "dark"
backgroundColor          = "#080808"
secondaryBackgroundColor = "#0f0f0f"
primaryColor             = "#00ff88"
textColor                = "#f0f0f0"
font                     = "sans serif"

[server]
headless = true

[ui]
hideTopBar = true
