[theme]
base                     = "dark"
backgroundColor          = "#08080c"
secondaryBackgroundColor = "#101014"
primaryColor             = "#3b82f6"
textColor                = "#f1f1f3"
font                     = "sans serif"

[server]
headless = true
